### ISSUE TITLE
Improve the vector-data-model figure

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap-book#4]
It would be great to reproduce the blow figure from https://www.earthdatascience.org/courses/earth-analytics/spatial-data-r/intro-vector-data-r/ using R code entirely. 

![](https://www.earthdatascience.org/images/courses/earth-analytics/spatial-data/spatial-attribute-tables.png)

The is a code chunk  `vector-data-model` from https://github.com/r-tmap/tmap-book/blob/master/02-geodata.Rmd, which can be used as a starting point.

**Comment by fguilhaumon** [comment]
Amaized by the skills deployment to produce figs in R code.

Was visually distracted by the tables having different heights (thus equal rows heights), I believe the version proposed on August 25 is more neat and les distracting visually speaking.

Thks for developping this, looking forward for v4.
